# Generated by Django 2.1.4 on 2019-04-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveuserdetails',
            name='confirmPassword',
        ),
    ]
